url: https://y7kim.github.io
baseurl: 

# Site settings
title: MobiCore Robotics
email: administration@mobicorerobotics.ca
description: "MobiCore Robotics is a pioneer"


# Team names, titles and social links
people:
- name: David Caron
  pic: david_caron
  position: CEO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/david-caron-b97955175/

- name: Kevin Larochelle
  pic: kevin_larochelle
  position: Directeur mécanique
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/kevin-larochelle/

- name: Amber Louie
  pic: amber_louie
  position: Directeur électronique et système
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/amber-louie-4137b91a9/
- name: Simon Roy
  pic: simon_roy
  position: CTO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/simonroy99/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty